const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  darkMode: 'class',
  content: [
    './config/initializers/**/*.rb',
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}'
  ],
  safelist: [
    // This is generated by rails i18n so it gets tree-shaked
    'translation_missing',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var',
               ...defaultTheme.fontFamily.sans],
      },
      colors: {
      },
    },
  },
  daisyui: {
    themes: [
      {
        lukin: {
          "primary": "#ec4899", // pink-500
          "primary-focus": "#db2777", // pink-600
          "secondary": "#a855f7", // purple-500
          "secondary-focus": "#9333ea", // purple-600
          "accent": "#3b82f6", // blue-500
          "neutral": "#1f2937", // gray-800
          "base-100": "#111827", // gray-900
          "info": "#3b82f6", // blue-500
          "success": "#10b981", // emerald-500
          "warning": "#f59e0b", // amber-500
          "error": "#ef4444", // red-500
        },
      },
    ],
  },
  plugins: [
    require('daisyui'),
    require('@tailwindcss/typography'),
    require('tailwindcss-safe-area')
  ],
}
